default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASS', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  database: placeholder_blogs_development

test:
  <<: *default
  database: placeholder_blogs_test

production:
  <<: *default
  database: placeholder_blogs_production
  username: placeholder_blogs
  password: <%= ENV["PLACEHOLDER_BLOGS_DATABASE_PASSWORD"] %>
